spring:
  application:
    name: CONFIG-SERVER


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
    registerWithEureka: true
    fetchRegistry: true
    instance:
      preferIpAddress: true

